# nyaturingtest/config.py
import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from nonebot import logger


PLUGIN_DIR = Path(__file__).parent
CONFIG_FILE = PLUGIN_DIR / "config.json"

DEEPSEEK_BASE_URL = "https://api.deepseek.com"
DEEPSEEK_COMPAT_BASE_URL = "https://api.deepseek.com/v1"
DEEPSEEK_CHAT_MODEL = "deepseek-v4-flash"
OPENAI_COMPATIBLE = "openai_compatible"
DEEPSEEK_OFFICIAL = "deepseek_official"
REMOVED_PROVIDER = "google" + "_ai_studio"

_plugin_config: dict[str, Any] = {}


@dataclass(frozen=True)
class EndpointSettings:
    provider: str
    api_key: str
    base_url: str
    model: str
    timeout: float
    max_tokens: int = 0
    thinking_enabled: bool = False
    reasoning_effort: str = ""
    rp_style: str = "off"


@dataclass(frozen=True)
class PluginSettings:
    chat: EndpointSettings
    feedback: EndpointSettings
    vlm: EndpointSettings
    rerank_model: str
    rerank_threshold: float


@dataclass(frozen=True)
class ConfigLoadStatus:
    ok: bool
    source: str
    path: str
    error_type: str = ""
    error_message: str = ""


_config_load_status = ConfigLoadStatus(ok=True, source="not_loaded", path=str(CONFIG_FILE))


def _set_config_load_status(
    *,
    ok: bool,
    source: str,
    error: Exception | None = None,
) -> None:
    global _config_load_status
    _config_load_status = ConfigLoadStatus(
        ok=ok,
        source=source,
        path=str(CONFIG_FILE),
        error_type=type(error).__name__ if error else "",
        error_message=str(error)[:300] if error else "",
    )


def get_config_load_status() -> ConfigLoadStatus:
    return _config_load_status


def get_default_config() -> dict:
    """返回默认配置"""
    return {
        "chat": {
            "provider": DEEPSEEK_OFFICIAL,
            "api_key": "",
            "base_url": DEEPSEEK_BASE_URL,
            "model": DEEPSEEK_CHAT_MODEL,
            "thinking": {
                "enabled": True,
                "reasoning_effort": "high",
                # off | deepseek_v4_roleplay
                "rp_style": "off",
            },
            "max_tokens": 4096,
            "timeout": 180,
        },
        "vlm": {
            "enabled": True,
            "provider": OPENAI_COMPATIBLE,
            "api_key": "",
            "base_url": "https://api.siliconflow.cn/v1",
            "model": "zai-org/GLM-4.6V",
            "timeout": 60,
        },
        "feedback": {
            "provider": DEEPSEEK_OFFICIAL,
            "api_key": "",
            "base_url": DEEPSEEK_BASE_URL,
            "model": DEEPSEEK_CHAT_MODEL,
            "thinking": {
                "enabled": False,
            },
            "max_tokens": 2048,
            "timeout": 60,
        },
        "siliconflow_api_key": "",
        "embedding": {
            "model": "BAAI/bge-m3",
            "base_url": "https://api.siliconflow.cn/v1",
            "timeout": 30,
        },
        "rerank": {
            "model": "Qwen/Qwen3-Reranker-4B",
            "base_url": "https://api.siliconflow.cn/v1/rerank",
            "timeout": 10,
            "threshold": 0.1,
        },
        "token_stats": {
            "watermark": "Generated by HakuBot",
        },
        "runtime": {
            "debounce_seconds": 2.0,
            "queue_max_size": 200,
            "send_strategy": "split_by_sentence",
            "max_reply_messages": 2,
            "humanized_delay_seconds": 1.0,
            "low_willingness_observe_interval": 5,
            "role_max_chars": 4000,
            "examples_max_chars": 2000,
            "short_context_limit": 20,
            "interaction_log_recent_days": 180,
            "history_recall_limit": 20,
            "speak_cooldown_seconds": 16.0,
            "willingness_idle_after_seconds": 300.0,
            "willingness_decay_rate_active": 0.03,
            "willingness_decay_rate_idle": 0.06,
            "relevance_willingness_floor": 0.95,
            "passive_willingness_growth_limit": 0.72,
            "passive_willingness_growth_per_message": 0.045,
            "low_willingness_skip_threshold": 0.30,
            "post_feedback_skip_threshold": 0.34,
            "rerank_willingness_threshold": 0.68,
        },
        "enabled_groups": [],
    }


def _deep_merge(default: dict[str, Any], loaded: dict[str, Any]) -> dict[str, Any]:
    result = dict(default)
    for key, value in loaded.items():
        if isinstance(value, dict) and isinstance(result.get(key), dict):
            result[key] = _deep_merge(result[key], value)
        else:
            result[key] = value
    return result


def _drop_removed_fields(section: dict[str, Any]) -> None:
    for key in (
        "google" + "_api_key",
        "google" + "_base_url",
    ):
        section.pop(key, None)


def _migrate_legacy_config(config: dict[str, Any]) -> dict[str, Any]:
    migrated = dict(config)
    vlm = dict(migrated.get("vlm") or {})
    if "openai_api_key" in vlm:
        vlm["api_key"] = vlm.get("openai_api_key") or vlm.get("api_key", "")
    if "openai_base_url" in vlm:
        vlm["base_url"] = vlm.get("openai_base_url") or vlm.get("base_url", "")
    vlm.pop("openai_api_key", None)
    vlm.pop("openai_base_url", None)
    if vlm:
        migrated["vlm"] = vlm
    return migrated


def _normalize_endpoint(section_name: str, section: dict[str, Any]) -> None:
    provider = str(section.get("provider") or "").strip().lower()
    base_url = str(section.get("base_url") or "").strip().rstrip("/")

    if provider == REMOVED_PROVIDER:
        raise RuntimeError(f"{section_name}.provider points to a removed provider; use DeepSeek official or OpenAI-compatible.")

    if section_name in {"chat", "feedback"}:
        if provider == OPENAI_COMPATIBLE and base_url in {DEEPSEEK_BASE_URL, DEEPSEEK_COMPAT_BASE_URL}:
            section["provider"] = DEEPSEEK_OFFICIAL
        elif provider not in {DEEPSEEK_OFFICIAL, OPENAI_COMPATIBLE}:
            raise RuntimeError(f"Unsupported {section_name}.provider: {provider}")
    elif section_name == "vlm":
        if provider != OPENAI_COMPATIBLE:
            raise RuntimeError("vlm.provider only supports OpenAI-compatible endpoints.")

    _drop_removed_fields(section)


def normalize_config(config: dict[str, Any]) -> dict[str, Any]:
    merged = _deep_merge(get_default_config(), _migrate_legacy_config(config))

    vlm = merged.get("vlm", {})
    vlm.pop("openai_api_key", None)
    vlm.pop("openai_base_url", None)

    _normalize_endpoint("chat", merged["chat"])
    _normalize_endpoint("feedback", merged["feedback"])
    _normalize_endpoint("vlm", merged["vlm"])

    return merged


def _require(value: str, field_name: str) -> str:
    value = (value or "").strip()
    if not value:
        raise RuntimeError(f"Missing required config field: {field_name}")
    return value


def build_settings(config: dict[str, Any], *, require_api_keys: bool = False) -> PluginSettings:
    cfg = normalize_config(config)

    def endpoint(name: str, *, require_key: bool, max_tokens_default: int = 0) -> EndpointSettings:
        section = cfg[name]
        api_key = section.get("api_key", "")
        if require_key:
            api_key = _require(api_key, f"{name}.api_key")
        base_url = _require(section.get("base_url", ""), f"{name}.base_url")
        model = _require(section.get("model", ""), f"{name}.model")
        thinking = section.get("thinking") or {}
        return EndpointSettings(
            provider=section.get("provider", ""),
            api_key=api_key,
            base_url=base_url,
            model=model,
            timeout=float(section.get("timeout") or 60),
            max_tokens=int(section.get("max_tokens") or max_tokens_default),
            thinking_enabled=bool(thinking.get("enabled", False)),
            reasoning_effort=str(thinking.get("reasoning_effort") or ""),
            rp_style=str(thinking.get("rp_style") or "off"),
        )

    return PluginSettings(
        chat=endpoint("chat", require_key=require_api_keys, max_tokens_default=4096),
        feedback=endpoint("feedback", require_key=require_api_keys, max_tokens_default=2048),
        vlm=endpoint("vlm", require_key=require_api_keys and bool(cfg.get("vlm", {}).get("enabled", True))),
        rerank_model=str(cfg.get("rerank", {}).get("model") or ""),
        rerank_threshold=float(cfg.get("rerank", {}).get("threshold") or 0.0),
    )


def describe_settings(settings: PluginSettings) -> str:
    def endpoint(name: str, value: EndpointSettings) -> str:
        key_state = "set" if value.api_key else "missing"
        return f"{name}: provider={value.provider}, model={value.model}, base_url={value.base_url}, api_key={key_state}"

    return "; ".join([
        endpoint("chat", settings.chat),
        endpoint("feedback", settings.feedback),
        endpoint("vlm", settings.vlm),
    ])


def load_plugin_config() -> dict:
    """从 config.json 加载插件配置"""
    global _plugin_config

    if not CONFIG_FILE.exists():
        logger.warning(f"配置文件不存在，将创建默认配置: {CONFIG_FILE}")
        _plugin_config = get_default_config()
        save_plugin_config(_plugin_config)
        _set_config_load_status(ok=True, source="default_created")
        return _plugin_config

    try:
        with open(CONFIG_FILE, "r", encoding="utf-8") as f:
            loaded = json.load(f)
        _plugin_config = normalize_config(loaded)
        settings = build_settings(_plugin_config, require_api_keys=False)
        _set_config_load_status(ok=True, source="file")
        logger.info(f"已加载插件配置: {CONFIG_FILE}")
        logger.info(f"插件配置摘要: {describe_settings(settings)}")
        return _plugin_config
    except RuntimeError as e:
        _set_config_load_status(ok=False, source="invalid", error=e)
        raise
    except Exception as e:
        logger.error(f"加载配置文件失败: {e}，使用默认配置")
        _plugin_config = get_default_config()
        _set_config_load_status(ok=False, source="fallback", error=e)
        return _plugin_config


def save_plugin_config(config: dict):
    """保存配置到 config.json"""
    try:
        with open(CONFIG_FILE, "w", encoding="utf-8") as f:
            json.dump(config, f, indent=2, ensure_ascii=False)
        logger.info(f"配置已保存: {CONFIG_FILE}")
    except Exception as e:
        logger.error(f"保存配置文件失败: {e}")


plugin_config = load_plugin_config()


def get_effective_chat_api_key() -> str:
    return plugin_config.get("chat", {}).get("api_key", "").strip()


def get_effective_chat_model() -> str:
    return (plugin_config.get("chat", {}).get("model") or DEEPSEEK_CHAT_MODEL).strip()


def get_effective_chat_base_url() -> str:
    return (plugin_config.get("chat", {}).get("base_url") or DEEPSEEK_BASE_URL).strip()


def get_effective_chat_provider() -> str:
    return (plugin_config.get("chat", {}).get("provider") or DEEPSEEK_OFFICIAL).strip().lower()


def get_chat_thinking_settings() -> dict[str, Any]:
    thinking = plugin_config.get("chat", {}).get("thinking") or {}
    return {
        "enabled": bool(thinking.get("enabled", True)),
        "reasoning_effort": str(thinking.get("reasoning_effort") or "low"),
        "rp_style": str(thinking.get("rp_style") or "off"),
    }


def get_chat_timeout() -> float:
    return float(plugin_config.get("chat", {}).get("timeout") or 180)


def get_chat_max_tokens() -> int:
    return int(plugin_config.get("chat", {}).get("max_tokens") or 1536)


def get_effective_feedback_api_key() -> str:
    return plugin_config.get("feedback", {}).get("api_key", "").strip()


def get_effective_feedback_model() -> str:
    return (plugin_config.get("feedback", {}).get("model") or DEEPSEEK_CHAT_MODEL).strip()


def get_effective_feedback_base_url() -> str:
    return (plugin_config.get("feedback", {}).get("base_url") or DEEPSEEK_BASE_URL).strip()


def get_effective_feedback_provider() -> str:
    return (plugin_config.get("feedback", {}).get("provider") or DEEPSEEK_OFFICIAL).strip().lower()


def get_feedback_thinking_settings() -> dict[str, Any]:
    thinking = plugin_config.get("feedback", {}).get("thinking") or {}
    return {"enabled": bool(thinking.get("enabled", False))}


def get_feedback_timeout() -> float:
    return float(plugin_config.get("feedback", {}).get("timeout") or 60)


def get_feedback_max_tokens() -> int:
    return int(plugin_config.get("feedback", {}).get("max_tokens") or 2048)


def get_effective_vlm_api_key() -> str:
    return plugin_config.get("vlm", {}).get("api_key", "").strip()


def get_effective_vlm_base_url() -> str:
    return plugin_config.get("vlm", {}).get("base_url", "").strip()


def get_effective_vlm_model() -> str:
    return plugin_config.get("vlm", {}).get("model", "").strip()


def get_token_stats_model_names() -> list[str]:
    models = [
        get_effective_chat_model(),
        get_effective_feedback_model(),
    ]
    if plugin_config.get("vlm", {}).get("enabled", True):
        models.append(get_effective_vlm_model())

    result = []
    seen = set()
    for model in models:
        if model and model not in seen:
            result.append(model)
            seen.add(model)
    return result


def get_runtime_settings() -> dict[str, Any]:
    runtime = plugin_config.get("runtime", {}) or {}

    def number(name: str, default, cast, *, minimum=None, maximum=None):
        value = runtime.get(name, default)
        if value is None or value == "":
            value = default
        try:
            value = cast(value)
        except (TypeError, ValueError):
            value = cast(default)
        if minimum is not None and value < minimum:
            value = minimum
        if maximum is not None and value > maximum:
            value = maximum
        return value

    def ratio(name: str, default: float) -> float:
        return number(name, default, float, minimum=0.0, maximum=1.0)

    return {
        "debounce_seconds": number("debounce_seconds", 2.0, float, minimum=0.0),
        "queue_max_size": number("queue_max_size", 200, int, minimum=1),
        "send_strategy": str(runtime.get("send_strategy") or "split_by_sentence"),
        "max_reply_messages": number("max_reply_messages", 2, int, minimum=1),
        "humanized_delay_seconds": number("humanized_delay_seconds", 1.0, float, minimum=0.0),
        "low_willingness_observe_interval": number("low_willingness_observe_interval", 5, int, minimum=0),
        "role_max_chars": number("role_max_chars", 4000, int, minimum=1),
        "examples_max_chars": number("examples_max_chars", 2000, int, minimum=0),
        "short_context_limit": number("short_context_limit", 20, int, minimum=1),
        "interaction_log_recent_days": number("interaction_log_recent_days", 180, int, minimum=1),
        "history_recall_limit": number("history_recall_limit", 20, int, minimum=1),
        "speak_cooldown_seconds": number("speak_cooldown_seconds", 16.0, float, minimum=0.0),
        "willingness_idle_after_seconds": number("willingness_idle_after_seconds", 300.0, float, minimum=0.0),
        "willingness_decay_rate_active": number("willingness_decay_rate_active", 0.03, float, minimum=0.0),
        "willingness_decay_rate_idle": number("willingness_decay_rate_idle", 0.06, float, minimum=0.0),
        "relevance_willingness_floor": ratio("relevance_willingness_floor", 0.95),
        "passive_willingness_growth_limit": ratio("passive_willingness_growth_limit", 0.72),
        "passive_willingness_growth_per_message": number("passive_willingness_growth_per_message", 0.045, float, minimum=0.0),
        "low_willingness_skip_threshold": ratio("low_willingness_skip_threshold", 0.30),
        "post_feedback_skip_threshold": ratio("post_feedback_skip_threshold", 0.34),
        "rerank_willingness_threshold": ratio("rerank_willingness_threshold", 0.68),
    }


def get_memory_endpoint_settings() -> dict[str, str | float]:
    embedding = plugin_config.get("embedding", {}) or {}
    rerank = plugin_config.get("rerank", {}) or {}
    return {
        "model": str(embedding.get("model") or "BAAI/bge-m3"),
        "base_url": str(embedding.get("base_url") or "https://api.siliconflow.cn/v1").rstrip("/"),
        "timeout": float(embedding.get("timeout") or 30),
        "rerank_base_url": str(rerank.get("base_url") or "https://api.siliconflow.cn/v1/rerank").rstrip("/"),
        "rerank_timeout": float(rerank.get("timeout") or 10),
    }
