# nyaturingtest/config.py
import json
from pathlib import Path
from typing import Any

from nonebot import logger

# 插件目录
PLUGIN_DIR = Path(__file__).parent
CONFIG_FILE = PLUGIN_DIR / "config.json"

# 全局配置对象
_plugin_config: dict[str, Any] = {}


def get_default_config() -> dict:
    """返回默认配置"""
    return {
        "chat": {
            "provider": "openai_compatible",
            "api_key": "",
            "base_url": "https://api.siliconflow.cn/v1",
            "model": "Qwen/Qwen3-32B",
            "google_api_key": "",
            "google_base_url": "https://generativelanguage.googleapis.com/v1beta"
        },
        "vlm": {
            "enabled": True,
            "provider": "openai_compatible",
            "model": "gemini-3-flash-preview",
            "openai_api_key": "",
            "openai_base_url": "",
            "google_api_key": "",
            "google_base_url": "https://generativelanguage.googleapis.com/v1beta"
        },
        "feedback": {
            "provider": "openai_compatible",
            "api_key": "",
            "base_url": "",
            "model": "Qwen/Qwen2.5-7B-Instruct",
            "google_api_key": "",
            "google_base_url": "https://generativelanguage.googleapis.com/v1beta"
        },
        "siliconflow_api_key": "",
        "rerank": {
            "model": "BAAI/bge-reranker-v2-m3",
            "threshold": 0.05
        },
        "token_stats": {
            "watermark": "Generated by HakuBot"
        },
        "enabled_groups": []
    }


def load_plugin_config() -> dict:
    """从 config.json 加载插件配置"""
    global _plugin_config
    
    if not CONFIG_FILE.exists():
        logger.warning(f"配置文件不存在，将创建默认配置: {CONFIG_FILE}")
        _plugin_config = get_default_config()
        save_plugin_config(_plugin_config)
        return _plugin_config
    
    try:
        with open(CONFIG_FILE, "r", encoding="utf-8") as f:
            _plugin_config = json.load(f)
        logger.info(f"已加载插件配置: {CONFIG_FILE}")
        return _plugin_config
    except Exception as e:
        logger.error(f"加载配置文件失败: {e}，使用默认配置")
        _plugin_config = get_default_config()
        return _plugin_config


def save_plugin_config(config: dict):
    """保存配置到 config.json"""
    try:
        with open(CONFIG_FILE, "w", encoding="utf-8") as f:
            json.dump(config, f, indent=2, ensure_ascii=False)
        logger.info(f"配置已保存: {CONFIG_FILE}")
    except Exception as e:
        logger.error(f"保存配置文件失败: {e}")


# 在模块加载时读取配置
plugin_config = load_plugin_config()


# ==================== Chat 配置辅助函数 ====================

def get_effective_chat_api_key() -> str:
    return plugin_config.get("chat", {}).get("api_key", "").strip()


def get_effective_chat_model() -> str:
    return (plugin_config.get("chat", {}).get("model") or "Qwen/Qwen3-32B").strip()


def get_effective_chat_base_url() -> str:
    return plugin_config.get("chat", {}).get("base_url", "").strip()


# ==================== Feedback 配置辅助函数 ====================

def get_effective_feedback_api_key() -> str:
    return plugin_config.get("feedback", {}).get("api_key", "").strip()


def get_effective_feedback_model() -> str:
    return (plugin_config.get("feedback", {}).get("model") or "Qwen/Qwen2.5-7B-Instruct").strip()


def get_effective_feedback_base_url() -> str:
    return plugin_config.get("feedback", {}).get("base_url", "").strip()
